include:
  - path: ./elite/docker-compose.yml
  - path: ./event/docker-compose.yml
  - path: ./project-overview/docker-compose.yml
  - path: ./gold/docker-compose.yml

services:
  nginx-proxy:
    container_name: nginx-proxy
    image: nginx:stable
    ports:
      - "443:443"
    volumes:
      - ./crt/wrkspace.dev.crt:/crt/wrkspace.dev.crt
      - ./crt/wrkspace.dev.pem:/crt/wrkspace.dev.pem
      - ./elite/elite.conf:/etc/nginx/conf.d/elite.conf
      - ./event/event.conf:/etc/nginx/conf.d/event.conf
      - ./gold/gold.conf:/etc/nginx/conf.d/gold.conf
      - ./project-overview/project-overview.conf:/etc/nginx/conf.d/project-overview.conf
    networks:
      - vps-network


networks:
  vps-network:
    external: true