services:
  nginx-proxy:
    container_name: nginx-proxy
    image: nginx:stable
    ports:
      - "127.0.0.1:8080:443"
    volumes:
      - ./elite.conf:/etc/nginx/conf.d/elite.conf
      - ./project-overview.conf:/etc/nginx/conf.d/project-overview.conf
    networks:
      - vps-network

  project-overview:
    container_name: project-overview
    image: moh080203/project-overview:latest
    networks:
      - vps-network


networks:
  vps-network:
    driver: bridge
